// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/org/mskcc/smile/commons/proto/smile.proto
// Protobuf Java Version: 4.26.1

package org.mskcc.smile.commons.models;

public final class Smile {
  private Smile() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Smile.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TempoSampleUpdateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mskcc.smile.commons.models.TempoSampleUpdateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    java.util.List<org.mskcc.smile.commons.models.Smile.TempoSample> 
        getTempoSamplesList();
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    org.mskcc.smile.commons.models.Smile.TempoSample getTempoSamples(int index);
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    int getTempoSamplesCount();
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    java.util.List<? extends org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder> 
        getTempoSamplesOrBuilderList();
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder getTempoSamplesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.mskcc.smile.commons.models.TempoSampleUpdateMessage}
   */
  public static final class TempoSampleUpdateMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mskcc.smile.commons.models.TempoSampleUpdateMessage)
      TempoSampleUpdateMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TempoSampleUpdateMessage.class.getName());
    }
    // Use TempoSampleUpdateMessage.newBuilder() to construct.
    private TempoSampleUpdateMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TempoSampleUpdateMessage() {
      tempoSamples_ = java.util.Collections.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.class, org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.Builder.class);
    }

    public static final int TEMPOSAMPLES_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<org.mskcc.smile.commons.models.Smile.TempoSample> tempoSamples_;
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public java.util.List<org.mskcc.smile.commons.models.Smile.TempoSample> getTempoSamplesList() {
      return tempoSamples_;
    }
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder> 
        getTempoSamplesOrBuilderList() {
      return tempoSamples_;
    }
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public int getTempoSamplesCount() {
      return tempoSamples_.size();
    }
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public org.mskcc.smile.commons.models.Smile.TempoSample getTempoSamples(int index) {
      return tempoSamples_.get(index);
    }
    /**
     * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
     */
    @java.lang.Override
    public org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder getTempoSamplesOrBuilder(
        int index) {
      return tempoSamples_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < tempoSamples_.size(); i++) {
        output.writeMessage(1, tempoSamples_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < tempoSamples_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, tempoSamples_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage)) {
        return super.equals(obj);
      }
      org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage other = (org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage) obj;

      if (!getTempoSamplesList()
          .equals(other.getTempoSamplesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getTempoSamplesCount() > 0) {
        hash = (37 * hash) + TEMPOSAMPLES_FIELD_NUMBER;
        hash = (53 * hash) + getTempoSamplesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mskcc.smile.commons.models.TempoSampleUpdateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mskcc.smile.commons.models.TempoSampleUpdateMessage)
        org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.class, org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.Builder.class);
      }

      // Construct using org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (tempoSamplesBuilder_ == null) {
          tempoSamples_ = java.util.Collections.emptyList();
        } else {
          tempoSamples_ = null;
          tempoSamplesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_descriptor;
      }

      @java.lang.Override
      public org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage getDefaultInstanceForType() {
        return org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.getDefaultInstance();
      }

      @java.lang.Override
      public org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage build() {
        org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage buildPartial() {
        org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage result = new org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage result) {
        if (tempoSamplesBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            tempoSamples_ = java.util.Collections.unmodifiableList(tempoSamples_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.tempoSamples_ = tempoSamples_;
        } else {
          result.tempoSamples_ = tempoSamplesBuilder_.build();
        }
      }

      private void buildPartial0(org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage) {
          return mergeFrom((org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage other) {
        if (other == org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage.getDefaultInstance()) return this;
        if (tempoSamplesBuilder_ == null) {
          if (!other.tempoSamples_.isEmpty()) {
            if (tempoSamples_.isEmpty()) {
              tempoSamples_ = other.tempoSamples_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureTempoSamplesIsMutable();
              tempoSamples_.addAll(other.tempoSamples_);
            }
            onChanged();
          }
        } else {
          if (!other.tempoSamples_.isEmpty()) {
            if (tempoSamplesBuilder_.isEmpty()) {
              tempoSamplesBuilder_.dispose();
              tempoSamplesBuilder_ = null;
              tempoSamples_ = other.tempoSamples_;
              bitField0_ = (bitField0_ & ~0x00000001);
              tempoSamplesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTempoSamplesFieldBuilder() : null;
            } else {
              tempoSamplesBuilder_.addAllMessages(other.tempoSamples_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                org.mskcc.smile.commons.models.Smile.TempoSample m =
                    input.readMessage(
                        org.mskcc.smile.commons.models.Smile.TempoSample.parser(),
                        extensionRegistry);
                if (tempoSamplesBuilder_ == null) {
                  ensureTempoSamplesIsMutable();
                  tempoSamples_.add(m);
                } else {
                  tempoSamplesBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<org.mskcc.smile.commons.models.Smile.TempoSample> tempoSamples_ =
        java.util.Collections.emptyList();
      private void ensureTempoSamplesIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          tempoSamples_ = new java.util.ArrayList<org.mskcc.smile.commons.models.Smile.TempoSample>(tempoSamples_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          org.mskcc.smile.commons.models.Smile.TempoSample, org.mskcc.smile.commons.models.Smile.TempoSample.Builder, org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder> tempoSamplesBuilder_;

      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public java.util.List<org.mskcc.smile.commons.models.Smile.TempoSample> getTempoSamplesList() {
        if (tempoSamplesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(tempoSamples_);
        } else {
          return tempoSamplesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public int getTempoSamplesCount() {
        if (tempoSamplesBuilder_ == null) {
          return tempoSamples_.size();
        } else {
          return tempoSamplesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public org.mskcc.smile.commons.models.Smile.TempoSample getTempoSamples(int index) {
        if (tempoSamplesBuilder_ == null) {
          return tempoSamples_.get(index);
        } else {
          return tempoSamplesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder setTempoSamples(
          int index, org.mskcc.smile.commons.models.Smile.TempoSample value) {
        if (tempoSamplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTempoSamplesIsMutable();
          tempoSamples_.set(index, value);
          onChanged();
        } else {
          tempoSamplesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder setTempoSamples(
          int index, org.mskcc.smile.commons.models.Smile.TempoSample.Builder builderForValue) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.set(index, builderForValue.build());
          onChanged();
        } else {
          tempoSamplesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(org.mskcc.smile.commons.models.Smile.TempoSample value) {
        if (tempoSamplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(value);
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(
          int index, org.mskcc.smile.commons.models.Smile.TempoSample value) {
        if (tempoSamplesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(index, value);
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(
          org.mskcc.smile.commons.models.Smile.TempoSample.Builder builderForValue) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(builderForValue.build());
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder addTempoSamples(
          int index, org.mskcc.smile.commons.models.Smile.TempoSample.Builder builderForValue) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.add(index, builderForValue.build());
          onChanged();
        } else {
          tempoSamplesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder addAllTempoSamples(
          java.lang.Iterable<? extends org.mskcc.smile.commons.models.Smile.TempoSample> values) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, tempoSamples_);
          onChanged();
        } else {
          tempoSamplesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder clearTempoSamples() {
        if (tempoSamplesBuilder_ == null) {
          tempoSamples_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          tempoSamplesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public Builder removeTempoSamples(int index) {
        if (tempoSamplesBuilder_ == null) {
          ensureTempoSamplesIsMutable();
          tempoSamples_.remove(index);
          onChanged();
        } else {
          tempoSamplesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public org.mskcc.smile.commons.models.Smile.TempoSample.Builder getTempoSamplesBuilder(
          int index) {
        return getTempoSamplesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder getTempoSamplesOrBuilder(
          int index) {
        if (tempoSamplesBuilder_ == null) {
          return tempoSamples_.get(index);  } else {
          return tempoSamplesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public java.util.List<? extends org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder> 
           getTempoSamplesOrBuilderList() {
        if (tempoSamplesBuilder_ != null) {
          return tempoSamplesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(tempoSamples_);
        }
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public org.mskcc.smile.commons.models.Smile.TempoSample.Builder addTempoSamplesBuilder() {
        return getTempoSamplesFieldBuilder().addBuilder(
            org.mskcc.smile.commons.models.Smile.TempoSample.getDefaultInstance());
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public org.mskcc.smile.commons.models.Smile.TempoSample.Builder addTempoSamplesBuilder(
          int index) {
        return getTempoSamplesFieldBuilder().addBuilder(
            index, org.mskcc.smile.commons.models.Smile.TempoSample.getDefaultInstance());
      }
      /**
       * <code>repeated .org.mskcc.smile.commons.models.TempoSample tempoSamples = 1;</code>
       */
      public java.util.List<org.mskcc.smile.commons.models.Smile.TempoSample.Builder> 
           getTempoSamplesBuilderList() {
        return getTempoSamplesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.mskcc.smile.commons.models.Smile.TempoSample, org.mskcc.smile.commons.models.Smile.TempoSample.Builder, org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder> 
          getTempoSamplesFieldBuilder() {
        if (tempoSamplesBuilder_ == null) {
          tempoSamplesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.mskcc.smile.commons.models.Smile.TempoSample, org.mskcc.smile.commons.models.Smile.TempoSample.Builder, org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder>(
                  tempoSamples_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          tempoSamples_ = null;
        }
        return tempoSamplesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:org.mskcc.smile.commons.models.TempoSampleUpdateMessage)
    }

    // @@protoc_insertion_point(class_scope:org.mskcc.smile.commons.models.TempoSampleUpdateMessage)
    private static final org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage();
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TempoSampleUpdateMessage>
        PARSER = new com.google.protobuf.AbstractParser<TempoSampleUpdateMessage>() {
      @java.lang.Override
      public TempoSampleUpdateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TempoSampleUpdateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TempoSampleUpdateMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mskcc.smile.commons.models.Smile.TempoSampleUpdateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TempoSampleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.mskcc.smile.commons.models.TempoSample)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string primaryId = 1;</code>
     * @return The primaryId.
     */
    java.lang.String getPrimaryId();
    /**
     * <code>string primaryId = 1;</code>
     * @return The bytes for primaryId.
     */
    com.google.protobuf.ByteString
        getPrimaryIdBytes();

    /**
     * <code>string cmoSampleName = 2;</code>
     * @return The cmoSampleName.
     */
    java.lang.String getCmoSampleName();
    /**
     * <code>string cmoSampleName = 2;</code>
     * @return The bytes for cmoSampleName.
     */
    com.google.protobuf.ByteString
        getCmoSampleNameBytes();

    /**
     * <code>bool embargoStatus = 3;</code>
     * @return The embargoStatus.
     */
    boolean getEmbargoStatus();

    /**
     * <code>string custodianInformation = 4;</code>
     * @return The custodianInformation.
     */
    java.lang.String getCustodianInformation();
    /**
     * <code>string custodianInformation = 4;</code>
     * @return The bytes for custodianInformation.
     */
    com.google.protobuf.ByteString
        getCustodianInformationBytes();
  }
  /**
   * Protobuf type {@code org.mskcc.smile.commons.models.TempoSample}
   */
  public static final class TempoSample extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:org.mskcc.smile.commons.models.TempoSample)
      TempoSampleOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 1,
        /* suffix= */ "",
        TempoSample.class.getName());
    }
    // Use TempoSample.newBuilder() to construct.
    private TempoSample(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TempoSample() {
      primaryId_ = "";
      cmoSampleName_ = "";
      custodianInformation_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSample_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSample_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.mskcc.smile.commons.models.Smile.TempoSample.class, org.mskcc.smile.commons.models.Smile.TempoSample.Builder.class);
    }

    public static final int PRIMARYID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object primaryId_ = "";
    /**
     * <code>string primaryId = 1;</code>
     * @return The primaryId.
     */
    @java.lang.Override
    public java.lang.String getPrimaryId() {
      java.lang.Object ref = primaryId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        primaryId_ = s;
        return s;
      }
    }
    /**
     * <code>string primaryId = 1;</code>
     * @return The bytes for primaryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPrimaryIdBytes() {
      java.lang.Object ref = primaryId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        primaryId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CMOSAMPLENAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cmoSampleName_ = "";
    /**
     * <code>string cmoSampleName = 2;</code>
     * @return The cmoSampleName.
     */
    @java.lang.Override
    public java.lang.String getCmoSampleName() {
      java.lang.Object ref = cmoSampleName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cmoSampleName_ = s;
        return s;
      }
    }
    /**
     * <code>string cmoSampleName = 2;</code>
     * @return The bytes for cmoSampleName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCmoSampleNameBytes() {
      java.lang.Object ref = cmoSampleName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cmoSampleName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMBARGOSTATUS_FIELD_NUMBER = 3;
    private boolean embargoStatus_ = false;
    /**
     * <code>bool embargoStatus = 3;</code>
     * @return The embargoStatus.
     */
    @java.lang.Override
    public boolean getEmbargoStatus() {
      return embargoStatus_;
    }

    public static final int CUSTODIANINFORMATION_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object custodianInformation_ = "";
    /**
     * <code>string custodianInformation = 4;</code>
     * @return The custodianInformation.
     */
    @java.lang.Override
    public java.lang.String getCustodianInformation() {
      java.lang.Object ref = custodianInformation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        custodianInformation_ = s;
        return s;
      }
    }
    /**
     * <code>string custodianInformation = 4;</code>
     * @return The bytes for custodianInformation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCustodianInformationBytes() {
      java.lang.Object ref = custodianInformation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        custodianInformation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(primaryId_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, primaryId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cmoSampleName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, cmoSampleName_);
      }
      if (embargoStatus_ != false) {
        output.writeBool(3, embargoStatus_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(custodianInformation_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, custodianInformation_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(primaryId_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, primaryId_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(cmoSampleName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, cmoSampleName_);
      }
      if (embargoStatus_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, embargoStatus_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(custodianInformation_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, custodianInformation_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.mskcc.smile.commons.models.Smile.TempoSample)) {
        return super.equals(obj);
      }
      org.mskcc.smile.commons.models.Smile.TempoSample other = (org.mskcc.smile.commons.models.Smile.TempoSample) obj;

      if (!getPrimaryId()
          .equals(other.getPrimaryId())) return false;
      if (!getCmoSampleName()
          .equals(other.getCmoSampleName())) return false;
      if (getEmbargoStatus()
          != other.getEmbargoStatus()) return false;
      if (!getCustodianInformation()
          .equals(other.getCustodianInformation())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PRIMARYID_FIELD_NUMBER;
      hash = (53 * hash) + getPrimaryId().hashCode();
      hash = (37 * hash) + CMOSAMPLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getCmoSampleName().hashCode();
      hash = (37 * hash) + EMBARGOSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getEmbargoStatus());
      hash = (37 * hash) + CUSTODIANINFORMATION_FIELD_NUMBER;
      hash = (53 * hash) + getCustodianInformation().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSample parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSample parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static org.mskcc.smile.commons.models.Smile.TempoSample parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.mskcc.smile.commons.models.Smile.TempoSample prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.mskcc.smile.commons.models.TempoSample}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.mskcc.smile.commons.models.TempoSample)
        org.mskcc.smile.commons.models.Smile.TempoSampleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSample_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSample_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.mskcc.smile.commons.models.Smile.TempoSample.class, org.mskcc.smile.commons.models.Smile.TempoSample.Builder.class);
      }

      // Construct using org.mskcc.smile.commons.models.Smile.TempoSample.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        primaryId_ = "";
        cmoSampleName_ = "";
        embargoStatus_ = false;
        custodianInformation_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.mskcc.smile.commons.models.Smile.internal_static_org_mskcc_smile_commons_models_TempoSample_descriptor;
      }

      @java.lang.Override
      public org.mskcc.smile.commons.models.Smile.TempoSample getDefaultInstanceForType() {
        return org.mskcc.smile.commons.models.Smile.TempoSample.getDefaultInstance();
      }

      @java.lang.Override
      public org.mskcc.smile.commons.models.Smile.TempoSample build() {
        org.mskcc.smile.commons.models.Smile.TempoSample result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.mskcc.smile.commons.models.Smile.TempoSample buildPartial() {
        org.mskcc.smile.commons.models.Smile.TempoSample result = new org.mskcc.smile.commons.models.Smile.TempoSample(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(org.mskcc.smile.commons.models.Smile.TempoSample result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.primaryId_ = primaryId_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cmoSampleName_ = cmoSampleName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.embargoStatus_ = embargoStatus_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.custodianInformation_ = custodianInformation_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.mskcc.smile.commons.models.Smile.TempoSample) {
          return mergeFrom((org.mskcc.smile.commons.models.Smile.TempoSample)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.mskcc.smile.commons.models.Smile.TempoSample other) {
        if (other == org.mskcc.smile.commons.models.Smile.TempoSample.getDefaultInstance()) return this;
        if (!other.getPrimaryId().isEmpty()) {
          primaryId_ = other.primaryId_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCmoSampleName().isEmpty()) {
          cmoSampleName_ = other.cmoSampleName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getEmbargoStatus() != false) {
          setEmbargoStatus(other.getEmbargoStatus());
        }
        if (!other.getCustodianInformation().isEmpty()) {
          custodianInformation_ = other.custodianInformation_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                primaryId_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                cmoSampleName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                embargoStatus_ = input.readBool();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                custodianInformation_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object primaryId_ = "";
      /**
       * <code>string primaryId = 1;</code>
       * @return The primaryId.
       */
      public java.lang.String getPrimaryId() {
        java.lang.Object ref = primaryId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          primaryId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string primaryId = 1;</code>
       * @return The bytes for primaryId.
       */
      public com.google.protobuf.ByteString
          getPrimaryIdBytes() {
        java.lang.Object ref = primaryId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          primaryId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string primaryId = 1;</code>
       * @param value The primaryId to set.
       * @return This builder for chaining.
       */
      public Builder setPrimaryId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        primaryId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string primaryId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrimaryId() {
        primaryId_ = getDefaultInstance().getPrimaryId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string primaryId = 1;</code>
       * @param value The bytes for primaryId to set.
       * @return This builder for chaining.
       */
      public Builder setPrimaryIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        primaryId_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object cmoSampleName_ = "";
      /**
       * <code>string cmoSampleName = 2;</code>
       * @return The cmoSampleName.
       */
      public java.lang.String getCmoSampleName() {
        java.lang.Object ref = cmoSampleName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cmoSampleName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cmoSampleName = 2;</code>
       * @return The bytes for cmoSampleName.
       */
      public com.google.protobuf.ByteString
          getCmoSampleNameBytes() {
        java.lang.Object ref = cmoSampleName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cmoSampleName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cmoSampleName = 2;</code>
       * @param value The cmoSampleName to set.
       * @return This builder for chaining.
       */
      public Builder setCmoSampleName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cmoSampleName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string cmoSampleName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCmoSampleName() {
        cmoSampleName_ = getDefaultInstance().getCmoSampleName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string cmoSampleName = 2;</code>
       * @param value The bytes for cmoSampleName to set.
       * @return This builder for chaining.
       */
      public Builder setCmoSampleNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cmoSampleName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private boolean embargoStatus_ ;
      /**
       * <code>bool embargoStatus = 3;</code>
       * @return The embargoStatus.
       */
      @java.lang.Override
      public boolean getEmbargoStatus() {
        return embargoStatus_;
      }
      /**
       * <code>bool embargoStatus = 3;</code>
       * @param value The embargoStatus to set.
       * @return This builder for chaining.
       */
      public Builder setEmbargoStatus(boolean value) {

        embargoStatus_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>bool embargoStatus = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmbargoStatus() {
        bitField0_ = (bitField0_ & ~0x00000004);
        embargoStatus_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object custodianInformation_ = "";
      /**
       * <code>string custodianInformation = 4;</code>
       * @return The custodianInformation.
       */
      public java.lang.String getCustodianInformation() {
        java.lang.Object ref = custodianInformation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          custodianInformation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string custodianInformation = 4;</code>
       * @return The bytes for custodianInformation.
       */
      public com.google.protobuf.ByteString
          getCustodianInformationBytes() {
        java.lang.Object ref = custodianInformation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          custodianInformation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string custodianInformation = 4;</code>
       * @param value The custodianInformation to set.
       * @return This builder for chaining.
       */
      public Builder setCustodianInformation(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        custodianInformation_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string custodianInformation = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCustodianInformation() {
        custodianInformation_ = getDefaultInstance().getCustodianInformation();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string custodianInformation = 4;</code>
       * @param value The bytes for custodianInformation to set.
       * @return This builder for chaining.
       */
      public Builder setCustodianInformationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        custodianInformation_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.mskcc.smile.commons.models.TempoSample)
    }

    // @@protoc_insertion_point(class_scope:org.mskcc.smile.commons.models.TempoSample)
    private static final org.mskcc.smile.commons.models.Smile.TempoSample DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.mskcc.smile.commons.models.Smile.TempoSample();
    }

    public static org.mskcc.smile.commons.models.Smile.TempoSample getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TempoSample>
        PARSER = new com.google.protobuf.AbstractParser<TempoSample>() {
      @java.lang.Override
      public TempoSample parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TempoSample> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TempoSample> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.mskcc.smile.commons.models.Smile.TempoSample getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_mskcc_smile_commons_models_TempoSample_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_mskcc_smile_commons_models_TempoSample_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n7src/main/java/org/mskcc/smile/commons/" +
      "proto/smile.proto\022\036org.mskcc.smile.commo" +
      "ns.models\"]\n\030TempoSampleUpdateMessage\022A\n" +
      "\014tempoSamples\030\001 \003(\0132+.org.mskcc.smile.co" +
      "mmons.models.TempoSample\"l\n\013TempoSample\022" +
      "\021\n\tprimaryId\030\001 \001(\t\022\025\n\rcmoSampleName\030\002 \001(" +
      "\t\022\025\n\rembargoStatus\030\003 \001(\010\022\034\n\024custodianInf" +
      "ormation\030\004 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mskcc_smile_commons_models_TempoSampleUpdateMessage_descriptor,
        new java.lang.String[] { "TempoSamples", });
    internal_static_org_mskcc_smile_commons_models_TempoSample_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_mskcc_smile_commons_models_TempoSample_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_org_mskcc_smile_commons_models_TempoSample_descriptor,
        new java.lang.String[] { "PrimaryId", "CmoSampleName", "EmbargoStatus", "CustodianInformation", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
